### ISSUE TITLE
Missing bitcode files

### ISSUE THREAD

**Issue by dvdplm** [PLSysSec/haybale-pitchfork#2]
Looks like there are a few bitcode files missing from the tests: [basic.bc](https://github.com/PLSysSec/haybale-pitchfork/blob/master/tests/ct_haybale.rs#L30) and [memory.bc](https://github.com/PLSysSec/haybale-pitchfork/blob/master/tests/ct_haybale.rs#L63).

Can add? :)

**Comment by cdisselkoen** [comment]
My bad.  You may have noticed that the test code looks for these files at `../haybale` - it expects `haybale` checked out as a sibling to Pitchfork, which doesn't make sense for end users.  Makes much more sense to check in those bitcode files here as you suggest.
