### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by ddealmei** [PLSysSec/haybale-pitchfork#4]
Hi,
I was try to use the [return_secret](https://docs.rs/haybale-pitchfork/0.3.0/haybale_pitchfork/hooks/fn.return_secret.html) and [propagate_taint](https://docs.rs/haybale-pitchfork/0.3.0/haybale_pitchfork/hooks/fn.propagate_taint.html) hooks from pitchfork but they do not seem to have the expected effect. In fact, they seems to behave like the generic hook (hence the returned value is always considered public).

Here is the C code I am testing:
```c
int dummy_func(char sec, size_t pub_len) {
	return sec;
}

int test_hook(char *secret, size_t len) {
	int k = dummy_func(secret[0], len);
	if (k == 0)
		return 1;
	return 0;
}
```
The corresponding Rust code, used to test is:
```rust
use pitchfork::{AbstractData, Config, PitchforkConfig, StructDescriptions, check_for_ct_violation, Project, hooks};
use std::path::Path;

fn main() {
    let path = "/tmp/bc_files/";
    let entry_point = "test_hook";
    // Assume both my secret and my length are secret
    let signature = Some(vec![
            AbstractData::pub_pointer_to(AbstractData::array_of(AbstractData::secret(), 80)),
            AbstractData::secret(), 
        ]);

    let project = get_project(&path);
    let mut config = Config::default();
    // Set the function hook
    config.function_hooks.add("dummy_func", &hooks::return_secret);

	let result = check_for_ct_violation(
		entry_point, 
		&project, 
		signature,
		&StructDescriptions::new(),
		config, 
		&PitchforkConfig::default());
	println!("{}", result);	
}
```

which outputs 
```
Results for test_hook:

verified paths: 2
constant-time violations found: 0

Coverage stats:

  Block coverage of toplevel function (test_hook): 100.0%

test_hook is constant-time
```

Since I used `hooks::return_secret`, I would have expected `k` to be considered secret, and to detect a constant time violation. Am I missing something ?
For the record, testing it without hook correctly finds the constant time violation.

**Comment by cdisselkoen** [comment]
Yep, this was a bug all right.  Thanks for posting an issue!  Should be fixed on `master` now, and I'll make a 0.3.1 release shortly.
